#!/bin/sh

# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

cwd=`dirname $0`

# databus-mapred Jar.
if [ ! -e $cwd/build/databus-mapred.jar ]; then
    echo "Unable to locate databus-mapred jar" >&2
    exit 1
fi

CLASSPATH=$CLASSPATH:$cwd/conf

for jar in $cwd/lib/*.jar; do
    CLASSPATH=$CLASSPATH:$jar
done

for jar in $cwd/build/*.jar; do
    CLASSPATH=$CLASSPATH:$jar
done

for jar in $cwd/build/lib/jars/*.jar; do
    CLASSPATH=$CLASSPATH:$jar
done



if [ -x $JAVA_HOME/bin/java ]; then
    JAVA=$JAVA_HOME/bin/java
else
    JAVA=`which java`
fi

if [ "x$JAVA" = "x" ]; then
    echo "Java executable not found (hint: set JAVA_HOME)" >&2
    exit 1
fi

OUTPUT_REDUCER=logger

echo $CLASSPATH
$JAVA -Xmx1G -ea -cp $CLASSPATH DatabusMapredTest output_reducer=$OUTPUT_REDUCER
#$JAVA -Xmx1G -ea -cp $CLASSPATH DatabusMapredTest -conf /Users/jcollins/Downloads/hadoop/hadoop-0.20.2/conf/mapred-site.xml output_reducer=$OUTPUT_REDUCER
